[tools]
biome = "latest"
bob = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
lua-language-server = "latest"
marksman = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@github/copilot" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:basedpyright" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:svelte-language-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:unocss-language-server" = "latest"
"npm:yaml-language-server" = "latest"
oxlint = "latest"
ruff = "latest"
rust = "latest"
stylua = "latest"
tinymist = "latest"
